<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_All Activity</name>
   <tag></tag>
   <elementGuidId>737d41ac-3e0f-44e3-8738-47ad64849e58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='uniqueId-0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#uniqueId-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>49f6bb84-c980-4464-963e-02c4a0e22b8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>626d66c6-32e7-4090-abea-ae48de769850</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>uniqueId-0</value>
      <webElementGuid>4be62113-17ed-4eec-836a-5a25e69cb650</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>0466e987-93e6-4eaa-ae96-dd3a6b51dfa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>18a3c846-5b42-493f-b13f-b159d6f43641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jsx-3430356839 btn-primary-billing active
                 btn-small btn-first</value>
      <webElementGuid>04d436e0-be5a-44b6-9003-cd3469357a0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>All Activity</value>
      <webElementGuid>a88374dc-8b84-4eba-9d90-3c4161dd621a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;uniqueId-0&quot;)</value>
      <webElementGuid>1da55718-234b-44d8-92a4-bcd75ec4fa35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='uniqueId-0']</value>
      <webElementGuid>8f6d0fa9-e2a3-4e74-9be9-68e0937b03c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div/div[3]/div/div/div/div[2]/div/button</value>
      <webElementGuid>d4aea462-8433-42dd-b944-36c99d7a4558</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('I', &quot;'&quot;, 'm searching for...')])[1]/following::button[1]</value>
      <webElementGuid>e8de373e-efa7-418e-84df-4fd87426d7f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Activity center'])[1]/following::button[1]</value>
      <webElementGuid>a160b139-befb-4325-a312-5870539b610e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bill'])[1]/preceding::button[1]</value>
      <webElementGuid>3ff75867-f9c5-4993-9067-e03c0ee3b2b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Payment'])[1]/preceding::button[2]</value>
      <webElementGuid>97ef8968-5bf5-4d12-967d-75b189a56982</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='All Activity']/parent::*</value>
      <webElementGuid>4f9776bf-8e2d-4d85-8323-4d7f9b5f2861</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button</value>
      <webElementGuid>8daa5bcc-f4b4-44e2-aefb-da9e919d2ca5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'uniqueId-0' and (text() = 'All Activity' or . = 'All Activity')]</value>
      <webElementGuid>70ff0e75-b915-4891-af5c-5e238b3e49d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
